spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employe
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1200
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG
